Konzept für Gleichheit von Datentypen mit/ohne SourceSpans
hsfl-pltp/language-java pull request #10
Opened 2023-05-04 21:34 UTC by mario-koehler

Dies ist noch kein compilierfähiger Stand, sondern nur ein erster Entwurf zum Review.

2023-05-04 21:40 UTC, mario-koehler commented
In einem Programm, welches die Library verwendet, könnten dann z.B.:
```
eq IncludeSourceSpan id1 id2
eqList IgnoreSourceSpan ids1 ids2
```
verwendet werden.

2023-05-05 07:55 UTC, jan-christiansen requested changes

2023-05-05 07:55 UTC, jan-christiansen commented on Language/Java/Syntax/Equality.hs
> +  | IncludeSourceSpan
Ich würde den Typ `EqOptions` nennen.

2023-05-05 07:55 UTC, jan-christiansen commented on Language/Java/Syntax/Equality.hs
> +class Localized a => Equality a where
Die Abhängigkeit von `Localized` finde ich nicht so gut. Es kann ja eine Struktur geben, die selbst keinen `SourceSpan` enthält, bei der man aber für die Kinder den `SourceSpan` berücksichtigen möchte. Ich würde die Klasse `Equality` jetzt für alle AST-Konstrukte als Ersatz für `Eq` nutzen. Ich finde, dass es insgesamt eine gute Sache ist, dass man sich bewusst ist, ob man die `SourceSpan`s berücksichtigt oder nicht. Die Implementierung der Instanzen für die ganzen Datentypen würde relativ viel _Boilerplate Code_ erzeugen, damit würde ich aber erst mal leben. Ggf. könnte man sich später Gedanken machen, ob man den Code mittels _Template Haskell_ oder ähnlichem generiert, also einen eigenen _Deriving_-Mechanismus nutzt.

2023-05-06 15:23 UTC, mario-koehler commented
Ich habe die Erweiterung mit der `Located`-Klasse in einen neuen Branch ausgelagert, für den es einen separaten PR gibt.

2023-05-08 14:22 UTC, jan-christiansen approved these changes

2023-05-08 14:23 UTC, merged